all:
  hosts:
    k8snode-1:
      ansible_host: 192.168.1.130
      ip: 192.168.1.130
      access_ip: 192.168.1.130
    k8snode-2:
      ansible_host: 192.168.1.131
      ip: 192.168.1.131
      access_ip: 192.168.1.131
    k8snode-3:
      ansible_host: 192.168.1.132
      ip: 192.168.1.132
      access_ip: 192.168.1.132
  children:
    kube_control_plane:
      hosts:
        k8snode-1:
    kube_node:
      hosts:
        k8snode-2:
        k8snode-3:
    etcd:
      hosts:
        k8snode-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}